//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aldelo.DatabaseInterface.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyMenuList = new HashSet<CompanyMenuList>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public int AddressId { get; set; }
        public int AccountId { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> PasswordExpireOn { get; set; }
        public string DBFolderPath { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyMenuList> CompanyMenuList { get; set; }
    }
}
