//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aldelo.DatabaseInterface.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMenuList
    {
        public int CompanyMenuListId { get; set; }
        public int CompanyId { get; set; }
        public int MenuId { get; set; }
        public byte Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
